services:
  mvc:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "secretPassword123"
      ACCEPT_EULA: "Y"
