services:
  api:
    build:
      context: .
      dockerfile: ./Blog.WebAPI/Dockerfile.API
    ports:
      - "5000:8000"
    depends_on:
      - db
      - redis_image
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"     
      
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "secretPassword123"
      ACCEPT_EULA: "Y"

  redis_image:
    image: "redis:latest"

  # ui:
  #   build:
  #     context: ./Blog.Frontend
  #     dockerfile: Dockerfile.UI
  #   ports: 
  #     - "5006:5007"
  #   depends_on:
  #     - api