version: "3"

services:
  api:
    container_name: the-blog_api

    build:
      context: .
      dockerfile: ./Blog.WebAPI/Dockerfile.API
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis_image
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"     
    restart: always

  db:
    container_name: the-blog_db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "secretPassword123"
      ACCEPT_EULA: "Y"    
    restart: always

  redis_image:
    container_name: the-blog_redis
    image: "redis:latest"
    restart: always

  ui:
    container_name: the-blog_ui
    build:
       context: ./Blog.Frontend
       dockerfile: Dockerfile.UI
     ports: 
       - "5006:80"
     depends_on:
       - api
    restart: always
