services:
  api:
    build:
      context: .
      dockerfile: ./Blog.WebAPI/Dockerfile.API
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"     
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "secretPassword123"
      ACCEPT_EULA: "Y"
  ui:
    build:
      context: ./Blog.Frontend
      dockerfile: Dockerfile.UI
    ports: 
      - "5006:80"
    depends_on:
      - api