services:
  mvc:
    image: blogcompose.azurecr.io/the-blog
    build: .   
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "secretPassword123"
      ACCEPT_EULA: "Y"
