services:
  api:
    build:
      context: .
      dockerfile: ./Blog.WebAPI/Dockerfile.API
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis_image
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"     
      
  redis_image:
    image: "redis:latest"

  ui:
     build:
       context: ./Blog.Frontend
       dockerfile: Dockerfile.UI
     ports: 
       - "5006:80"
     depends_on:
       - api