version: "3"

services:
  the-blog_api:
    container_name: the-blog_api

    build:
      context: .
      dockerfile: ./Blog.WebAPI/Dockerfile.API
    ports:
      - "8000:8000"
    depends_on:
      # - db
      - the-blog_redis_image
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"     
      ConnectionStrings__BlogDatabase: ${PSQL_CONN}
      ConnectionStrings__IdentityDatabase: ${PSQL_CONN}

  # db:
  #   container_name: the-blog_db
    
  #   image: "mcr.microsoft.com/mssql/server:2022-latest"
  #   environment:
  #     SA_PASSWORD: "secretPassword123"
  #     ACCEPT_EULA: "Y"    
  #   restart: always

  the-blog_redis_image:
    container_name: the-blog_redis
    image: "redis:latest"
    restart: always

  the-blog_ui:
    container_name: the-blog_ui

    build:
       context: ./Blog.Frontend
       dockerfile: Dockerfile.UI
    ports: 
       - "5006:80"
    depends_on:
       - the-blog_api
    restart: always
