name: GitHub Pages Deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: cd src/Blog.Frontend && npm install
      
    - name: Build
      run: cd src/Blog.Frontend && npm run build --   --configuration=production

    - name: Copy index.html to 404.html
      run: cd src/Blog.Frontend/dist/the-blog-front && cp index.html 404.html
      
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: src/Blog.Frontend/dist/the-blog-front/
        enable_jekyll: true
